my_campus_guide/guide/urls.py
from django.urls import path
from guide import views

app_name = 'guide'

urlpatterns = [
  path('', views.index, name='index'),
  path('courses/', views.courses, name='courses'),
  path('lecturers/', views.lecturers, name='lecturers'),
  path('register/', views.register, name='register'),
  path('registered/', views.registered, name='registered'),
  path('login/', views.login, name='login'),
  path('courses/add_course/', views.add_course, name='add_course'),
  path('lecturers/add_lecturer/', views.add_lecturer, name='add_lecturer'),
  path('lecturers/<slug:lecturer_name_slug>/', views.show_lecturer, name = "show_lecturer"),
  path('courses/<slug:course_name_slug>/', views.show_course, name = "show_course"),
  path('logout/', views.logout, name = 'logout'),
  path('myprofile/', views.myprofile, name = 'myprofile'),
  path('deleteuser/', views.deleteuser, name = 'delete_account'),
  path('lecturers/<slug:lecturer_name_slug>/edit/', views.edit_lecturer, name = "edit_lecturer"),
  path('courses/<slug:course_name_slug>/edit/', views.edit_course, name = "edit_course"),
  path('search_results/', views.searchResults, name = 'searchResults'),
]

my_campus_guide/my_campus_guide/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from guide import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index, name='index'),
    path('guide/', include('guide.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls')),
    #path('verification/', include('verify_email.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_campus_guide/guide/forms.py
from django import forms 
from guide.models import Course, Lecturer, LecturerRating, CourseRating, CourseComment, LecturerComment
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator 
from guide.models import UserProfile
import datetime




class UserDeleteForm(forms.ModelForm):
    class Meta:
        model = User
        fields = []  


class CourseForm(forms.ModelForm):
	name = forms.CharField( max_length=128,
						   help_text="Please enter the course name.") 
	school = forms.CharField(max_length=30,
						   help_text="Please enter the course's school.") 
	credits = forms.IntegerField( 
							help_text='Please enter how many credits the course is worth.') 
	requirements = forms.CharField(max_length=100,
						   help_text="Please enter the course requirements.")
	description = forms.CharField(max_length=200,
						   help_text="Please enter a short description of the course.")
	currentlecturer = forms.CharField(max_length=30,
						   help_text="Please enter the current lecturer.")
	views = forms.IntegerField(widget=forms.HiddenInput(), initial=0) 


	class Meta:
		model = Course
		fields = ('name', 'school', 'credits', 'requirements', 'description', 'currentlecturer')




class LecturerForm(forms.ModelForm):
	name = forms.CharField(max_length=50,
						   help_text="Please enter the lecturer's name.") 
	teaching = forms.CharField(max_length=100,
						   help_text="Please enter what the lecturer teaches.") 
	description = forms.CharField(max_length=280,
						   help_text="Please enter a short bio for the lecturer.")
	picture = forms.ImageField(help_text="Please enter an image for the lecturer.",
							required=False)

	views = forms.IntegerField(widget=forms.HiddenInput(), initial=0) 



	class Meta:
		model = Lecturer
		fields = ('name', 'teaching', 'description', 'picture')


class DateInput(forms.DateInput):
    input_type = 'date' 

class UserForm(forms.ModelForm):
	username = forms.CharField(max_length=30,
						   help_text="Please enter your username.") 
	email = forms.EmailField(max_length=254,
						   help_text="Please enter your Glasgow University email.") 
	password = forms.CharField(widget=forms.PasswordInput(),
						   help_text ="Please enter your password.")
	major = forms.CharField(max_length=30,
						   help_text="Please enter your major.")
	degreeprogram = forms.CharField(max_length=14,
						   help_text="Please enter your degree program.")
	startedstudying = forms.DateField(initial=datetime.date.today, 
							help_text='Please enter when you started studying.', widget=DateInput)
	expectedgraduation = forms.DateField(initial=datetime.date.today, 
							help_text='Please enter your expected graduation date.', widget=DateInput)
	picture = forms.ImageField(help_text="Please enter a picture", required=False)

	
	class Meta:
		model = User
		fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('major', 'picture', 'degreeprogram', 'startedstudying', 'expectedgraduation')


class LecturerRatingForm(forms.ModelForm):
	rating = forms.IntegerField( validators=[MinValueValidator(1), MaxValueValidator(5)])
	class Meta:
		model = LecturerRating
		fields = ('rating',)


class CourseRatingForm(forms.ModelForm):
	rating = forms.IntegerField( validators=[MinValueValidator(1), MaxValueValidator(5)])
	class Meta:
		model = CourseRating
		fields = ('rating',)

class LecturerCommentForm(forms.ModelForm):
	comment = forms.CharField(max_length=200)
	class Meta:
		model = LecturerComment
		fields = ('comment',)

class CourseCommentForm(forms.ModelForm):
	comment = forms.CharField(max_length=200)
	class Meta:
		model = CourseComment
		fields = ('comment',)

class ChangeProfileForm(forms.ModelForm):
	email = forms.CharField(max_length=254)
	major = forms.CharField(max_length=30)
	degreeprogram = forms.CharField(max_length=14)
	startedstudying = forms.DateField()
	expectedgraduation = forms.DateField()
	picture = forms.ImageField(required=False)
	class Meta:
		model = UserProfile
		fields = ('email', 'major', 'degreeprogram', 'startedstudying', 'expectedgraduation', 'picture')

class EditLecturer(forms.ModelForm):
	teaching = forms.CharField(max_length=100)
	description = forms.CharField(max_length=280)

	class Meta:
		model = Lecturer
		fields = ('teaching', 'description')

class EditCourse(forms.ModelForm):
	school = forms.CharField(max_length=30)
	credits = forms.IntegerField()
	requirements = forms.CharField(max_length=100)
	description = forms.CharField(max_length=200)
	currentlecturer = forms.CharField(max_length=30)


	class Meta:
		model = Course
		fields = ('school', 'credits', 'requirements', 'description', 'currentlecturer')

my_campus_guide/guide/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from guide.models import Lecturer, Course, UserProfile, LecturerRating, Category, CourseRating
from guide.forms import LecturerForm, CourseForm, UserForm, UserProfileForm, LecturerRatingForm, CourseRatingForm, LecturerCommentForm, CourseCommentForm, UserDeleteForm, ChangeProfileForm, EditLecturer, EditCourse
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.shortcuts import redirect
from django.urls import reverse
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import random
from django.contrib import messages

def visitor_cookie_handler(request, response): 
  visits = int(request.COOKIES.get('visits', '1'))
  last_visit_cookie = request.COOKIES.get('last_visit', str(datetime.now())) 
  last_visit_time = datetime.strptime(last_visit_cookie[:-7],'%Y-%m-%d %H:%M:%S')
  if (datetime.now() - last_visit_time).days > 0:
    visits = visits + 1
  else:
    response.set_cookie('visits', visits)


def index(request):
  response =  render(request, 'guide/index.html')
  try:
    #Get's the lecture and course with the most views to appear on 'trending'
    trending_lecturer = Lecturer.objects.order_by('-views')[0]
    trending_course = Course.objects.order_by('-views')[0]
  except:
    trending_lecturer = None
    trending_course = None
  context_dict = {}
  context_dict['lecturer'] = trending_lecturer
  context_dict['course'] = trending_course
  #Chooses a random picture to select on the trending page for the courses page
  context_dict['course_image'] = "course_"+str(random.randint(1,3))+".jpg"
  visitor_cookie_handler(request, response)
  return render(request, 'guide/index.html', context=context_dict)


@login_required
def myprofile(request):
    user = User.objects.get(username=request.user.username)
    profile = UserProfile.objects.get(user=request.user)
    #If its a HTTP POST, we are interested in processing form data
    if request.method == 'POST':
      form = ChangeProfileForm(request.POST)

      if form.is_valid():
        #Updates any changed information on the users profile page
        cform = form.save(commit=False)
        user.email = cform.email
        profile.major = cform.major
        profile.degreeprogram = cform.degreeprogram
        profile.startedstudying = cform.startedstudying
        profile.expectedgraduation = cform.expectedgraduation
        if 'picture' in request.FILES:
          profile.picture = request.FILES['picture']
        user.save()
        profile.save()
        
        #Refreshes the page
        return HttpResponseRedirect(request.path_info)

    return render(request, 'guide/myprofile.html', context={'user': user, 'profile': profile})

def courses(request):
  #Initially orders the courses by name to calculate the number of comments and average ratings for each
  courses = Course.objects.order_by('name')
  for course in courses:
    course.storeNumberOfComments()
    course.calculateAverageRating()
    course.save()
  #Whatever button the user presses to sort by, it orders it accordingly 
  order_by = request.GET.get('order_by', 'name')
  courses = Course.objects.order_by(order_by)  
  context_dict = {}
  context_dict['courses'] = courses
  return render(request, 'guide/courses.html', context=context_dict)

def lecturers(request):
  #Initially orders the lecturers by name to calculate the number of comments and average ratings for each
  lecturers = Lecturer.objects.order_by('name')
  for lecturer in lecturers:
    lecturer.storeNumberOfComments()
    lecturer.calculateAverageRating()
    lecturer.save()
  #Whatever button the user presses to sort by, it orders it accordingly 
  order_by = request.GET.get('order_by', 'name')
  lecturers = Lecturer.objects.order_by(order_by)  
  context_dict = {}
  context_dict['lecturers'] = lecturers
  return render(request, 'guide/lecturers.html', context=context_dict)

@login_required
def add_course(request):
  category = Category.objects.get(name="Course Pages")
  user = User.objects.get(username=request.user.username)

  form = CourseForm()
  if request.method == 'POST':
      form = CourseForm(request.POST)

      if form.is_valid():
        #Sets the attributes entered by the user for the course page
        page = form.save(commit=False)
        page.category = category
        page.views = 0
        page.page_owner = user
        page.save()
        #Redirects to courses page if successful
        return redirect(reverse('guide:courses'))
      else:
        print(form.errors)
  return render(request, 'guide/add_course.html', {'form':form})

@login_required
def add_lecturer(request):
  category = Category.objects.get(name="Lecturer Pages")
  user = User.objects.get(username=request.user.username)

  form = LecturerForm()
  if request.method == 'POST':
      form = LecturerForm(request.POST, request.FILES)

      if form.is_valid():
        #Sets the attributes entered by the user for the course page
        page = form.save(commit=False)
        page.category = category
        page.views = 0
        page.page_owner = user
        page.save()
        #Redirects to lecturers page if successful
        return redirect(reverse('guide:lecturers'))
      else:
        print(form.errors)
  return render(request, 'guide/add_lecturer.html', {'form':form})


def show_lecturer(request, lecturer_name_slug):
  context_dict = {}
  try:
    lecturer = Lecturer.objects.get(slug=lecturer_name_slug)
    lecturer.calculateAverageRating()
    lecturer.viewed()
    context_dict['lecturer'] = lecturer
    context_dict['comments'] = lecturer.lecturercomment_set.all()
    
    try:
      #Checks if the user already has a rating for this page to display if so
      user = User.objects.get(username=request.user.username) 
      context_dict['rating'] = LecturerRating.objects.get(user=user, page=lecturer)
    except:
      context_dict['rating'] = None

  except Lecturer.DoesNotExist:
    context_dict['lecturer'] = None
    context_dict['rating'] = None

  #Form for each the ratings and the comments
  form = LecturerRatingForm()
  cform = LecturerCommentForm()
  if request.method == 'POST':
    #The rating form is only processed if the data is in the request
    if 'submitrating' in request.POST:
      form = LecturerRatingForm(request.POST)

      if form.is_valid():
        rating = form.save(commit=False)
        rating.user = user
        rating.page = lecturer
        rating.save()
        context_dict['form'] = form
        context_dict['rating'] = LecturerRating.objects.get(user=user, page=lecturer)
        #Refreshes the page, removing information stored
        return HttpResponseRedirect(request.path_info)
    
    #The comment form is only processed if the data is in the request
    if 'submitcomment' in request.POST:
      cform = LecturerCommentForm(request.POST)
      if cform.is_valid():
        comment = cform.save(commit=False)
        comment.user = request.user
        comment.page = lecturer
        comment.save()
        context_dict['cform'] = cform 
        #Refreshes the page, removing information stored and empties the form  
        return HttpResponseRedirect(request.path_info)
  
  context_dict['cform'] = cform
  context_dict['form'] = form

  return render(request, 'guide/chosen_lecturer.html', context = context_dict)


def show_course(request, course_name_slug):
  context_dict = {}
  try:
    course = Course.objects.get(slug=course_name_slug)
    course.calculateAverageRating()
    course.viewed()
    context_dict['course'] = course
    context_dict['comments'] = course.coursecomment_set.all()

    try:
      #Checks if the user already has a rating for this page to display if so
      user = User.objects.get(username=request.user.username)  
      context_dict['rating'] = CourseRating.objects.get(user=user, page=course)
    except:
      context_dict['rating'] = None

  except Course.DoesNotExist:
    context_dict['course'] = None
    context_dict['rating'] = None

  #Form for each the ratings and the comments
  form = CourseRatingForm()
  cform = CourseCommentForm()
  if request.method == 'POST':
    #The rating form is only processed if the data is in the request
    if 'submitrating' in request.POST:
      form = CourseRatingForm(request.POST)

      if form.is_valid():
        rating = form.save(commit=False)
        rating.user = user
        rating.page = course
        rating.save()
        context_dict['form'] = form
        context_dict['rating'] = CourseRating.objects.get(user=user, page=course)
        #Refreshes the page, removing information stored
        return HttpResponseRedirect(request.path_info)
  
    #The comment form is only processed if the data is in the request
    if 'submitcomment' in request.POST:
      cform = CourseCommentForm(request.POST)
      if cform.is_valid():
        comment = cform.save(commit=False)
        comment.user = request.user
        comment.page = course
        comment.save()
        context_dict['cform'] = cform 
        #Refreshes the page, removing information stored and empties the form  
        return HttpResponseRedirect(request.path_info)
  
  context_dict['cform'] = cform
  context_dict['form'] = form

  return render(request, 'guide/chosen_course.html', context = context_dict)


def searchResults(request):
  context_dict = {}
  #Recieves search query by the user
  userSearch = request.GET.get('searchResults')
  users = UserProfile.objects.all()
  context_dict["user_profiles"] = users
  try:
      #Filters lecturer objects to only show those of which the characters in the user's search is within the lecturer's name
      lecturers = Lecturer.objects.filter(name__contains = userSearch)
      context_dict["searchlecturers"] = lecturers
      context_dict["SearchValue"] = userSearch
      

my_campus_guide/templates/guide/add_course.html
{% extends 'guide/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Add Course
{% endblock %}

{% block body_block %}
  <div class="jubmotron jumbotron-fluid">
    <div class="container">
      <h1 class="add_course_or_lecturer_title">Add Course</h1>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <form role="form" class="add_lecturer_or_course_form" method="post" action="{% url 'guide:add_course' %}"> 
        {% csrf_token %}
        {% for hidden in form.hidden_fields %} 
          {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
          {{ field.errors }}
          {{ field.help_text }}<br /> 
          {{ field }}<br />
          <div class="p-2"></div>
        {% endfor %} 
        <br />
        <button class="btn btn-primary standard_button" id="add_course_button" type="submit" name="submit"> 
          Add Course
        </button>
        <div class="p-5"></div> 
      </form>
    </div>
  </div>
{% endblock %}

my_campus_guide/templates/guide/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
      MyCampus Guide -
      {% block title_block %}
        Welcome!
      {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>	
    <link rel="stylesheet" type="text/css"    href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap5.min.css">
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-4  d-md-block bg-light sidebar">
          <div class="sidebar-sticky" id="navcolumn">
            <a href="{% url 'guide:index' %}"><img src="{% static 'images/logo.svg' %}" alt="MyCampus Guide" height="123" width="294" /></a>
            <form class="search-form" method="get" action="{% url 'guide:searchResults' %}">
              <input name="searchResults" type="search" id="search-text" placeholder="Search" aria-label="Search">
              <button type="submit" id="search-icon">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                  <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                </svg>
              </button>
            </form>

            <ul class="list-group">
              <li class="nav-item "><a class="nav-link" href="{% url 'guide:index' %}">Home</a></li>
              <li class="nav-item "><a class="nav-link" href="{% url 'guide:lecturers' %}">Lecturers</a></li>
              <li class="nav-item "><a class="nav-link" href="{% url 'guide:courses' %}">Courses</a></li>
            </ul>
            <ul class="list-group bottom">
              {% if user.is_authenticated %}
                <li class="nav-item "><a class="nav-link" href="{% url 'guide:logout' %}">Logout</a></li> 
                <li class="nav-item "><a class="nav-link" href="{% url 'guide:myprofile' %}">My Profile</a></li>  
              {% else %}
                <li class="nav-item "><a class="nav-link" href="{% url 'guide:login' %}">Login</a></li>
                <li class="nav-item "><a class="nav-link" href="{% url 'guide:register' %}">Register</a></li>
              {% endif %}
            </ul>
            <footer>&copy; WAD LB14d 2021</footer>
          </div>
        </nav>
        <main role="main" class="col-md-8 ml-sm-auto col-lg-10 px-4" id="contentWrapper">
          <div class="contentContainer">
            {% block body_block %}
            {% endblock %}
          </div>
        </main>
      </div>
    </div> 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script> 
  </body>
</html>

my_campus_guide/templates/guide/chosen_course.html
{% extends 'guide/base.html' %} 
{% load staticfiles %}

{% block title_block %} 
  {% if course %}
    {{ course.name }}
  {% else %}
    Unknown Course
  {% endif %}
{% endblock %}

{% block body_block %}
  <div class="jumbotron p-4"> 
    <div class="container">
      {% if course %}
        <h1 class="course_or_lecturer_title">{{ course.name }}</h1>
        <div class="course_description_block" id="course_description_right" >
          <p>{{ course.school }} - {{ course.year }}</p>
          <p>Credits: {{ course.credits }}</p>
          <p >Course Requirements: {{ course.requirements }}</p>
          <p>Current Lecturer: {{ course.currentlecturer }}</p>
          <p >Average Rating: {{ course.avg_rating }}/5
          {% if user.is_authenticated %}
            {% if rating %}
              <p >Your Rating: {{ rating.rating }}/5</p>
            {% else %}
              </br ></br >
              <form role="form" id="show_course" method="post" action="{% url 'guide:show_course' course.slug %}"> 
                {% csrf_token %}
                {% for field in form.visible_fields %}
                  <b>{{ field.errors }}</b>
                  <p>{{ field }} /5</p>
                {% endfor %} 
                <input type="submit" name="submitrating" value="Submit Rating"/>
              </form>
            {% endif %}  
          {% endif %}
        </div>

        <div class="course_description_block">
          <strong>{{ course.description }}</strong>
          <br>
          <br>

          {% if user.is_authenticated %}
            {% ifequal user course.user %}
              <div>
                <a class="standard_button" href="{% url 'guide:edit_course' course.slug %}">Edit</a>
              </div>
            {% endifequal %}								
            {% if user.is_superuser %}
              <div>
                <a class="standard_button" href="{% url 'guide:edit_course' course.slug %}">Edit</a>
              </div>
            {% endif %}								
          {% endif %}
        </div>
        <div class="comment_section"> 
          <h2>Comments</h2>
          {% if not user.is_authenticated %}
            <h6>To add a comment please 
              <a href="{% url 'guide:login' %}">Log In</a>
            </h6>
          {% endif %}
          {% if user.is_authenticated %}
            <form role="form" id="show_course" method="post" action="{% url 'guide:show_course' course.slug %}">
              {% csrf_token %}
              Add a comment: <input type="text" name="comment" value="" size="80" />
              <input type="submit" name="submitcomment" value="Submit Comment"/> 
            </form>
            </br >
          {% endif %}                   
          <div class="row">
          </div>
          {% if comments %}                             
            <div class="col">
              {% for comment in comments %}
                <div class="row">
                  <p>User: {{ comment.user }}, posted on: {{ comment.date }}<br>{{ comment.comment }}</p>
                </div>
              {% endfor %}
            </div>
          {%else%}
            <strong>No comments yet</strong>
          {% endif %} 
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

my_campus_guide/templates/guide/chosen_lecturer.html
{% extends 'guide/base.html' %} 
{% load staticfiles %}

{% block title_block %} 
  {% if lecturer %}
    {{ lecturer.name }}
  {% else %}
    Unknown Lecturer
  {% endif %}
{% endblock %}

{% block body_block %}      
  <div class="jumbotron p-4">        
    <script type="text/javascript" src="{% static 'js/forms.js' %}"></script>   
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
    <div class="container" onload="showImage()">
      {% if lecturer %}
        <h1 class="course_or_lecturer_title">{{ lecturer.name }}</h1>
        <div class="lecturer_description_block" id="lecturer_description_right">
          {% if lecturer.picture %}
            <p><img id="lecturer_image" src="{{ lecturer.picture.url }}" alt="Lecturer Image" class="trending lecturer_image" style="visibility:visible"></p>
            <input class="standard_button" id="showimage" type="button" onClick="showImage()" value="Show Image">
            <input class="standard_button" id="hideimage" type="button" onClick="hideImage()" value="Hide Image">
          {% else %}
            No picture uploaded
          {% endif %}
          <br>
          <br>
          <p>Currently Teaching: {{ lecturer.teaching }}</p>
          <p>Average Rating: {{ lecturer.avg_rating }}/5
          {% if user.is_authenticated %}
            {% if rating %}
              <p >Your Rating: {{ rating.rating }}/5</p>
            {% else %}
              </br ></br >
              <form role="form" id="show_lecturer" method="post" action="{% url 'guide:show_lecturer' lecturer.slug %}"> 
                {% csrf_token %}
                {% for field in form.visible_fields %}
                  <b>{{ field.errors }}</b>
                  <p>{{ field }} /5</p>
                {% endfor %} 
                <input type="submit" name="submitrating" value="Submit Rating"/>
              </form>
            {% endif %} 
          {% endif %}
        </div>
        <div class="lecturer_description_block">
          <p>{{ lecturer.description }}</p>

          {% if user.is_authenticated %}
            {% ifequal user course.user %}
              <div>
               <a class="standard_button" href="{% url 'guide:edit_lecturer' lecturer.slug %}">Edit</a>
              </div>
            {% endifequal %}								
            {% if user.is_superuser %}
              <div>
                <a class="standard_button" href="{% url 'guide:edit_lecturer' lecturer.slug %}">Edit</a>
              </div>
            {% endif %}								
          {% endif %}
        </div>
        <div class="comment_section"> 
          <h2>Comments</h2>
          {% if not user.is_authenticated %}
            <h6>To add a comment please 
              <a href="{% url 'guide:login' %}">Log In</a>
            </h6>
          {% endif %}
          {% if user.is_authenticated %}
            <form role="form" id="show_lecturer" method="post" action="{% url 'guide:show_lecturer' lecturer.slug %}">
              {% csrf_token %}
              Add a comment: <input type="text" name="comment" value="" size="80" />
              <input type="submit" name="submitcomment" value="Submit Comment"/> 
            </form>
            </br >
          {% endif %}                   
          <div class="row">
          </div>
          {% if comments %}                             
            <div class="col">
              {% for comment in comments %}
                <div class="row">
                  <p>User: {{ comment.user }}, posted on: {{ comment.date }}<br>{{ comment.comment }}</p>
                </div>
              {% endfor %}
            </div>
          {%else%}
            <strong>No comments yet</strong>
          {% endif %} 
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

my_campus_guide/templates/guide/index.html
{% extends 'guide/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Homepage
{% endblock %}

{% block body_block %}
  <div class="jubmotron jumbotron-fluid">
    <div class="container">
    <h1 class="pageTitle">Welcome
    {% if user.is_authenticated %}
      <span class="username" id="index_page_username">{{ user.username }} </span>
    {% endif %}
		</h1>
    {% if lecturer or course %}
      <h1 id="trending_h1">Trending</h1>
      <div class="row">
        {% if lecturer %}
          <div class="col index_page_div">
            <a href="{% url 'guide:show_lecturer' lecturer.slug %}">
              <h2>{{ lecturer.name }}</h2>
              {% if lecturer.picture %}
                <img src="{{ lecturer.picture.url }}" class="trending">
              {% endif %}
            </a>
          </div>
        {% endif %}
        {% if course %}
          <div class="col index_page_div">
            <a href="{% url 'guide:show_course' course.slug %}">
              <h2>{{ course.name }}</h2>
              <img src="{% static 'images/' %}{{ course_image }}" class="trending">
            </a>
          </div>
        {% endif %}
      </div>
    {% endif %}
    </div>
  </div>
{% endblock %}